name: Build Dist

on:
  push:
    branches:
      - main
      # - update
    tags:
      - "*.*.*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - name: Install packages
        run: npm install
      - name: Run tests
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set Env Vars
        id: set_env
        run: |
          dist_zip_file="dist-${GITHUB_REF_NAME}-${GITHUB_SHA:0:7}.zip"
          echo "DIST_ZIP_FILE=${dist_zip_file}" >> "$GITHUB_ENV"
          echo "dist_zip_file=${dist_zip_file}" >> "$GITHUB_OUTPUT"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - name: Install packages
        run: npm install
      - name: Build for Production
        run: |
          npm run build-prod
          zip -r "$DIST_ZIP_FILE" dist
          ls -la
      - name: Release Build
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.set_env.outputs.dist_zip_file }}
